### Equipo 7
#### Grupo: 002
#### Integrantes:
#### 1745134 Ramírez Arellano Nathanael
#### 1795417 Mendoza Sanchez Evelin Yamile
#### 1798181 Tello Esparza Jesus Omar

### 1) Página donde se encuentra la base de datos:
#### [Heart Failure Prediction](https://www.kaggle.com/andrewmvd/heart-failure-clinical-data)

## 2) Descripción de los datos.
### a) ¿Qué tipo de datos son? 
Base de datos en Excel (tablas) que muestra la información de la asociación de lo que causa una enfermedad cardiaca.


### b) Descripción de la columna
Age, anaemia, creatinine_phosphokinase, diabetes, ejection fraction, high_blood_pressure, platelets, serum creatinine, serum sodium, sex, smoking,  time, DEATH_EVENT.

## 3) Justificación del uso de datos.
### a) Cuáles fueron las características que les llamó la atención de los datos. Qué les hizo querer trabajar con ellos.
El análisis de como algunas enfermedades pueden influir a una muerte por una enfermedad cardiovascular.

### b) Qué beneficio encuentran de trabajar con estos datos.
b)	Informarnos más sobre el cómo las enfermedades mostradas tienen influencia en una enfermedad cardiovascular y tomar más conciencia de cómo las enfermedades pueden afectarnos a largo plazo.

## 4) Objetivo final.
### a) Explicar a detalle cual es el objetivo principal (y secundarios en caso de existir) para trabajar con este tipo de datos.
Que enfermedades tienen una mayor probabilidad a desembocar una muerte por enfermedades cardiovasculares.


## 5) Mencionar preguntas de interés.
### Plantear 2 preguntas de interés que se resolverán al finalizar el proyecto.
¿Cuáles son las causas de las enfermedades del corazón?
¿Cuáles son los factores de riesgo que se pueden controlar?
¿Cómo se pueden prevenir las enfermedades del corazón?

## 6) Parte de programación.

### Preparación de los datos

In [2]:
import pandas as pd
import numpy as np
import json

#llamamos el archivo de excel
heartbase = pd.read_csv("heart_failure_clinical_records_dataset.csv")

### Visualización de Datos

- Datos sin manipulación

In [9]:
heartbase

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0    75.0        0                       582         0                 20   
1    55.0        0                      7861         0                 38   
2    65.0        0                       146         0                 20   
3    50.0        1                       111         0                 20   
4    65.0        1                       160         1                 20   
..    ...      ...                       ...       ...                ...   
294  62.0        0                        61         1                 38   
295  55.0        0                      1820         0                 38   
296  45.0        0                      2060         1                 60   
297  45.0        0                      2413         0                 38   
298  50.0        0                       196         0                 45   

     high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                      1  265000.00               1.9           130    1   
1                      0  263358.03               1.1           136    1   
2                      0  162000.00               1.3           129    1   
3                      0  210000.00               1.9           137    1   
4                      0  327000.00               2.7           116    0   
..                   ...        ...               ...           ...  ...   
294                    1  155000.00               1.1           143    1   
295                    0  270000.00               1.2           139    0   
296                    0  742000.00               0.8           138    0   
297                    0  140000.00               1.4           140    1   
298                    0  395000.00               1.6           136    1   

     smoking  time  DEATH_EVENT  
0          0     4            1  
1          0     6            1  
2          1     7            1  
3          0     7            1  
4          0     8            1  
..       ...   ...          ...  
294        1   270            0  
295        0   271            0  
296        0   278            0  
297        1   280            0  
298        1   285            0  

[299 rows x 13 columns]

- Vemos el tamaño de la base de datos

In [18]:
heartbase.shape

(299, 13)

- Vemos los primeros 5 elementos de todas las columnas

In [19]:
heartbase.head()

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0  75.0        0                       582         0                 20   
1  55.0        0                      7861         0                 38   
2  65.0        0                       146         0                 20   
3  50.0        1                       111         0                 20   
4  65.0        1                       160         1                 20   

   high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    1  265000.00               1.9           130    1   
1                    0  263358.03               1.1           136    1   
2                    0  162000.00               1.3           129    1   
3                    0  210000.00               1.9           137    1   
4                    0  327000.00               2.7           116    0   

   smoking  time  DEATH_EVENT  
0        0     4            1  
1        0     6            1  
2        1     7            1  
3        0     7            1  
4        0     8            1

- Vemos los últimos 5 elementos de todas las columnas

In [26]:
heartbase.tail()

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
294  62.0        0                        61         1                 38   
295  55.0        0                      1820         0                 38   
296  45.0        0                      2060         1                 60   
297  45.0        0                      2413         0                 38   
298  50.0        0                       196         0                 45   

     high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
294                    1   155000.0               1.1           143    1   
295                    0   270000.0               1.2           139    0   
296                    0   742000.0               0.8           138    0   
297                    0   140000.0               1.4           140    1   
298                    0   395000.0               1.6           136    1   

     smoking  time  DEATH_EVENT  
294        1   270            0  
295        0   271            0  
296        0   278            0  
297        1   280            0  
298        1   285            0

- Verificamos los datos nulos (no los hay)

In [18]:
heartbase.isnull().any()

age                         False
anaemia                     False
creatinine_phosphokinase    False
diabetes                    False
ejection_fraction           False
high_blood_pressure         False
platelets                   False
serum_creatinine            False
serum_sodium                False
sex                         False
smoking                     False
time                        False
DEATH_EVENT                 False
dtype: bool

### Cambiar el nombre de las columnas
- En nuestro caso, modificamos los nombres de las columnas al idioma español

In [7]:
heartbase = heartbase.rename(columns = {'age':'Edad','anaemia':'Anemia','creatinine_phosphokinase':'Creatina_Fosfoquinasa','diabetes':'Diabetes','ejection_fraction':'Fraccion_de_Eyeccion',
                           'high_blood_pressure':'Hipertension','platelets':'Plaquetas','serum_creatinine':'Suero_de_Creatinina','serum_sodium':'Suero_de_Sodio','sex':'Sexo',
                           'smoking':'Fumador','time':'Tiempo','DEATH_EVENT':'Muerte'}) #los nombres de las columnas se modificaron al idioma español
#heartbase.rename(columns = {'anaemia':'Anemia')
#heartbase.rename(columns = 'creatinine_phosphokinase':'Creatina_Fosfoquinasa'})
#heartbase.rename(columns = {'diabetes':'Diabetes'})
#heartbase.rename(columns = {'ejection_fraction':'Fraccion_de_Eyeccion'})
#heartbase.rename(columns = {'high_blood_pressure':'Hipertension'})
#heartbase.rename(columns = {'platelets':'Plaquetas'})
#heartbase.rename(columns = {'serum_creatinine':'Suero_de_Creatinina'})
#heartbase.rename(columns = {'serum_sodium':'Suero_de_Sodio'})
#heartbase.rename(columns = {'sex':'Sexo'})
#heartbase.rename(columns = {'smoking':'Fumador'})
#eartbase.rename(columns = {'time':'Tiempo'})
#heartbase.rename(columns = {'DEATH_EVENT':'Muerte'})

### Descripción básica de columnas
- Vemos las columnas

In [8]:
heartbase.columns

Index(['Edad', 'Anemia', 'Creatina_Fosfoquinasa', 'Diabetes',
       'Fraccion_de_Eyeccion', 'Hipertension', 'Plaquetas',
       'Suero_de_Creatinina', 'Suero_de_Sodio', 'Sexo', 'Fumador', 'Tiempo',
       'Muerte'],
      dtype='object')

- Tipos de datos por columnas

In [9]:
heartbase.dtypes

Edad                     float64
Anemia                     int64
Creatina_Fosfoquinasa      int64
Diabetes                   int64
Fraccion_de_Eyeccion       int64
Hipertension               int64
Plaquetas                float64
Suero_de_Creatinina      float64
Suero_de_Sodio             int64
Sexo                       int64
Fumador                    int64
Tiempo                     int64
Muerte                     int64
dtype: object

- Elementos únicos de la columna 'Edad' (La edad del paciente)

In [10]:
print("Edad:")
heartbase.Edad.unique()

Edad:


array([75.   , 55.   , 65.   , 50.   , 90.   , 60.   , 80.   , 62.   ,
       45.   , 49.   , 82.   , 87.   , 70.   , 48.   , 68.   , 53.   ,
       95.   , 58.   , 94.   , 85.   , 69.   , 72.   , 51.   , 57.   ,
       42.   , 41.   , 67.   , 79.   , 59.   , 44.   , 63.   , 86.   ,
       66.   , 43.   , 46.   , 61.   , 81.   , 52.   , 64.   , 40.   ,
       60.667, 73.   , 77.   , 78.   , 54.   , 47.   , 56.   ])

- Elementos únicos de la columna 'Anemia' (Si el paciente tiene Anemia sí:1|no:0)

In [11]:
print("Anemia:")
heartbase.Anemia.unique()

Anemia:


array([0, 1], dtype=int64)

- Elementos únicos de la columna 'Creatina Fosfoquinasa' (Niveles de la enzima en mcg/L)

In [12]:
print("Creatina Fosfoquinasa:")
heartbase.Creatina_Fosfoquinasa.unique()

Creatina Fosfoquinasa:


array([ 582, 7861,  146,  111,  160,   47,  246,  315,  157,  123,   81,
        231,  981,  168,   80,  379,  149,  125,   52,  128,  220,   63,
        148,  112,  122,   60,   70,   23,  249,  159,   94,  855, 2656,
        235,  124,  571,  127,  588, 1380,  553,  129,  577,   91, 3964,
         69,  260,  371,   75,  607,  789,  364, 7702,  318,  109,   68,
        250,  110,  161,  113, 5882,  224,   92,  102,  203,  336,   76,
         55,  280,   78,   84,  115,   66,  897,  154,  144,  133,  514,
         59,  156,   61,  305,  898, 5209,   53,  328,  748, 1876,  936,
        292,  369,  143,  754,  400,   96,  737,  358,  200,  248,  270,
       1808, 1082,  719,  193, 4540,  646,  281, 1548,  805,  291,  482,
        943,  185,  132, 1610, 2261,  233,   30, 1846,  335,   58,  910,
         72,  130, 2334, 2442,  776,  196,  835, 3966,  171,  198,   95,
       1419,  478,  176,  395,   99,  145,  104, 1896,  151,  244,   62,
        121,  418,  167, 1211, 1767,  308,   97,   

- Elementos únicos de la columna 'Diabetes' (Si el paciente tiene diabetes sí:1|no:0)

In [13]:
print("Diabetes:")
heartbase.Diabetes.unique()

Diabetes:


array([0, 1], dtype=int64)

- Elementos únicos de la columna 'Fracción de Eyección' (Porcentaje de sangre que sale del corazón tras cada contracción)

In [14]:
print("Fracción de Eyección:")
heartbase.Fraccion_de_Eyeccion.unique()

Fracción de Eyección:


array([20, 38, 40, 15, 60, 65, 35, 25, 30, 50, 14, 55, 45, 62, 80, 17, 70],
      dtype=int64)

- Elementos únicos de la columna 'Hipertensión' (Si el paciente tiene hipertensión sí:1|no:0)

In [15]:
print("Hipertensión:")
heartbase.Hipertension.unique()

Hipertensión:


array([1, 0], dtype=int64)

- Elementos únicos de la columna 'Plaquetas' (Plaquetas en la sangre medido en kiloplaquetas/mL)

In [16]:
print("Plaquetas:")
heartbase.Plaquetas.unique()

Plaquetas:


array([265000.  , 263358.03, 162000.  , 210000.  , 327000.  , 204000.  ,
       127000.  , 454000.  , 388000.  , 368000.  , 253000.  , 136000.  ,
       276000.  , 427000.  ,  47000.  , 262000.  , 166000.  , 237000.  ,
        87000.  , 297000.  , 289000.  , 149000.  , 196000.  , 284000.  ,
       153000.  , 200000.  , 360000.  , 319000.  , 302000.  , 188000.  ,
       228000.  , 226000.  , 321000.  , 305000.  , 329000.  , 185000.  ,
       218000.  , 194000.  , 310000.  , 271000.  , 451000.  , 140000.  ,
       395000.  , 418000.  , 351000.  , 255000.  , 461000.  , 223000.  ,
       216000.  , 254000.  , 390000.  , 385000.  , 119000.  , 213000.  ,
       274000.  , 244000.  , 497000.  , 374000.  , 122000.  , 243000.  ,
       266000.  , 317000.  , 283000.  , 324000.  , 293000.  , 172000.  ,
       406000.  , 173000.  , 304000.  , 235000.  , 181000.  , 249000.  ,
       219000.  , 318000.  , 221000.  , 298000.  , 286000.  , 621000.  ,
       263000.  , 850000.  , 306000.  , 252000.  , 

- Elementos únicos de la columna 'Suero de Creatinina' (Niveles de este suero en la sangre medido en mg/dL)

In [17]:
print("Suero de Creatinina:")
heartbase.Suero_de_Creatinina.unique()

Suero de Creatinina:


array([1.9 , 1.1 , 1.3 , 2.7 , 2.1 , 1.2 , 1.5 , 9.4 , 4.  , 0.9 , 1.  ,
       0.8 , 1.6 , 1.83, 5.8 , 3.  , 3.5 , 2.3 , 0.6 , 4.4 , 1.4 , 6.8 ,
       2.2 , 2.  , 1.18, 2.9 , 0.7 , 1.7 , 2.5 , 1.8 , 3.2 , 0.75, 3.7 ,
       3.4 , 6.1 , 2.4 , 9.  , 5.  , 0.5 , 3.8 ])

- Elementos únicos de la columna 'Suero de Sodio' (Niveles de este suero en la sangre medido en mEq/L)

In [18]:
print("Suero de Sodio:")
heartbase.Suero_de_Sodio.unique()

Suero de Sodio:


array([130, 136, 129, 137, 116, 132, 131, 138, 133, 140, 127, 121, 135,
       134, 144, 128, 145, 142, 139, 146, 141, 143, 126, 124, 113, 125,
       148], dtype=int64)

- Elementos únicos de la columna 'Sexo' (Mujer:0|Hombre:1)

In [19]:
print("Sexo:")
heartbase.Sexo.unique()

Sexo:


array([1, 0], dtype=int64)

- Elementos únicos de la columna 'Fumador' (Si el paciente fumaba Sí:1|No:0)

In [20]:
print("Fumador:")
heartbase.Fumador.unique()

Fumador:


array([0, 1], dtype=int64)

- Elementos únicos de la columna 'Tiempo' (Periodo de tiempo donde observaban al paciente en días)

In [21]:
print("Tiempo:")
heartbase.Tiempo.unique()

Tiempo:


array([  4,   6,   7,   8,  10,  11,  12,  13,  14,  15,  16,  20,  22,
        23,  24,  26,  27,  28,  29,  30,  31,  32,  33,  35,  38,  40,
        41,  42,  43,  44,  45,  50,  54,  55,  59,  60,  61,  63,  64,
        65,  66,  67,  68,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  82,  83,  85,  86,  87,  88,  90,  91,  94,  95,  96,  97,
       100, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 115, 117,
       118, 119, 120, 121, 123, 126, 129, 130, 134, 135, 140, 145, 146,
       147, 148, 150, 154, 162, 170, 171, 172, 174, 175, 180, 185, 186,
       187, 188, 192, 193, 194, 195, 196, 197, 198, 200, 201, 205, 206,
       207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 220, 230, 231,
       233, 235, 237, 240, 241, 244, 245, 246, 247, 250, 256, 257, 258,
       270, 271, 278, 280, 285], dtype=int64)

- Elementos únicos de la columna 'Muerte' (Si el paciente murió durante el periodo de observación Sí:1|No:0)

In [22]:
print("Muerte:")
heartbase.Muerte.unique()

Muerte:


array([1, 0], dtype=int64)

- Eliminemos algunas columnas que no nos sirven (para la práctica de la limpieza de datos eliminaremos la columna de diabetes)

In [26]:
heartbase = heartbase.drop(['Diabetes'],axis =1) #para la práctica de la limpieza de datos eliminaremos la columna de diabetes
heartbase

Edad  Anemia  Creatina_Fosfoquinasa  Fraccion_de_Eyeccion  Hipertension  \
0    75.0       0                    582                    20             1   
1    55.0       0                   7861                    38             0   
2    65.0       0                    146                    20             0   
3    50.0       1                    111                    20             0   
4    65.0       1                    160                    20             0   
..    ...     ...                    ...                   ...           ...   
294  62.0       0                     61                    38             1   
295  55.0       0                   1820                    38             0   
296  45.0       0                   2060                    60             0   
297  45.0       0                   2413                    38             0   
298  50.0       0                    196                    45             0   

     Plaquetas  Suero_de_Creatinina  Suero_de_Sodio  Sexo  Fumador  Tiempo  \
0    265000.00                  1.9             130     1        0       4   
1    263358.03                  1.1             136     1        0       6   
2    162000.00                  1.3             129     1        1       7   
3    210000.00                  1.9             137     1        0       7   
4    327000.00                  2.7             116     0        0       8   
..         ...                  ...             ...   ...      ...     ...   
294  155000.00                  1.1             143     1        1     270   
295  270000.00                  1.2             139     0        0     271   
296  742000.00                  0.8             138     0        0     278   
297  140000.00                  1.4             140     1        1     280   
298  395000.00                  1.6             136     1        1     285   

     Muerte  
0         1  
1         1  
2         1  
3         1  
4         1  
..      ...  
294       0  
295       0  
296       0  
297       0  
298       0  

[299 rows x 12 columns]

### Clasificación y Agrupación de datos
- Agrupemos a las personas que sí murieron durante el periodo de observación

In [28]:
si_murio = heartbase[heartbase['Muerte']==1]
si_murio

Edad  Anemia  Creatina_Fosfoquinasa  Fraccion_de_Eyeccion  Hipertension  \
0    75.0       0                    582                    20             1   
1    55.0       0                   7861                    38             0   
2    65.0       0                    146                    20             0   
3    50.0       1                    111                    20             0   
4    65.0       1                    160                    20             0   
..    ...     ...                    ...                   ...           ...   
220  73.0       0                    582                    20             0   
230  60.0       0                    166                    30             0   
246  55.0       0                   2017                    25             0   
262  65.0       1                    258                    25             0   
266  55.0       0                   1199                    20             0   

     Plaquetas  Suero_de_Creatinina  Suero_de_Sodio  Sexo  Fumador  Tiempo  \
0    265000.00                 1.90             130     1        0       4   
1    263358.03                 1.10             136     1        0       6   
2    162000.00                 1.30             129     1        1       7   
3    210000.00                 1.90             137     1        0       7   
4    327000.00                 2.70             116     0        0       8   
..         ...                  ...             ...   ...      ...     ...   
220  263358.03                 1.83             134     1        0     198   
230   62000.00                 1.70             127     0        0     207   
246  314000.00                 1.10             138     1        0     214   
262  198000.00                 1.40             129     1        0     235   
266  263358.03                 1.83             134     1        1     241   

     Muerte  
0         1  
1         1  
2         1  
3         1  
4         1  
..      ...  
220       1  
230       1  
246       1  
262       1  
266       1  

[96 rows x 12 columns]

In [29]:
si_murio.to_csv('PacientesFallecidos.csv')

- Creamos un nuevo archivo con la base de datos editada

In [30]:
heartbase.to_csv('NuevaHeartBase.csv')

In [ ]:
Con esto terminamos la limpieza de datos y tenemos un nuevo archivo